### ISSUE TITLE
Package is using deprecated runtimes

### ISSUE THREAD

**Issue by CorruptComputer** [flathub/org.unitystation.StationHub#1]
Noticed this today after installing this package:

```
$ flatpak upgrade
Looking for updates…

Info: runtime org.freedesktop.Platform branch 20.08 is end-of-life, with reason:
   org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this runtime:
   org.unitystation.StationHub

Info: runtime org.freedesktop.Platform.GL.default branch 20.08 is end-of-life, with reason:
   org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   org.unitystation.StationHub
```

**Comment by CorruptComputer** [comment]
I think the fix for this should be as easy as changing this value to `22.08`: 
https://github.com/flathub/org.unitystation.StationHub/blob/master/org.unitystation.StationHub.yaml#L3

**Comment by CorruptComputer** [comment]
I also noticed that the GitHub URL in the package seems to be wrong: 
https://github.com/flathub/org.unitystation.StationHub/blob/master/org.unitystation.StationHub.yaml#L35

Shouldn't it be set to the main repo instead of someones fork of it? https://github.com/unitystation/stationhub

**Comment by CorruptComputer** [comment]
@alexlarsson @Elijahrane Apologies for the ping, just wanted to check if this is being worked on. I can open a PR to change these two lines, but I have no idea how to build it after making the change to test. The repo here has no build instructions for it.

**Comment by Elijahrane** [comment]
I'll probably just mark this as end-of-life because the project has almost completely died in favor of another one with the same goal in the years since then



> I also noticed that the GitHub URL in the package seems to be wrong: https://github.com/flathub/org.unitystation.StationHub/blob/master/org.unitystation.StationHub.yaml#L35
> 
> Shouldn't it be set to the main repo instead of someones fork of it? https://github.com/unitystation/stationhub

![image](https://user-images.githubusercontent.com/60792108/221378763-50aafbab-22d6-4549-95c8-a8ece9875716.png)

**Comment by CorruptComputer** [comment]
That project isn't dead though? It is still the officially recommended way to run UnityStation. 

Also that repo has no changes from what is upstream, everything that was there in the past is already merged into the upstream repo. So now it is just behind from what upstream has, with no other changes made to it.

**Comment by Elijahrane** [comment]
> It is still the officially recommended way to run UnityStation.

which is basically dead

> Also that repo has no changes from what is upstream

I could update it but with how much effort it took to set up last time and all of those sources and dotnet stuff that would need to get updated I don't think it's worth going through that again for something no one will use

https://github.com/flathub/org.unitystation.StationHub/blob/master/sources.json

if I wanted to keep up with updates I would have to come up with some way to autogenerate these. the initial one was like halfway automated and I had to correct the rest. there were a lot of strange exceptions with specific packages so it wasn't very smooth

**Comment by CorruptComputer** [comment]
> which is basically dead

UnityStation is not "basically dead", it is still being actively developed.

> I could update it but with how much effort it took to set up last time and all of those sources and dotnet stuff that would need to get updated I don't think it's worth going through that again for something no one will use

If updating it is more effort than you'd like to put in, why not try to find a new maintainer for this? If you provide some basic instructions for how to get it built I would even be willing to do so. As of right now there are no instructions for how you are supposed to build this anywhere in the repo.

**Comment by Elijahrane** [comment]
I'll look into transferring ownership to https://github.com/MaxIsJoe

>As of right now there are no instructions for how you are supposed to build this anywhere in the repo.

It's the same process for every flatpak no?

**Comment by CorruptComputer** [comment]
> I'll look into transferring ownership to https://github.com/MaxIsJoe

Just saw the conversation over in Discord, thank you!

> It's the same process for every flatpak no?

I have never built a flatpak, so I have no idea. I assumed they would be built differently based on the software they are packaging, but perhaps not. I'll have to take a look into that sometime when I have time to do so.

**Comment by Elijahrane** [comment]
Or I'll transfer to https://github.com/corp-0 rather
